models={

 ["Acura"] = {
      "CL",
      "ILX",
      "Integra",
      "Legend",
      "MDX",
      "RDX",
      "RL",
      "RSX",
      "SLX",
      "TL",
      "TSX",
      "Vigor",
      "ZDX",
 },
 ["Alfa Romeo"] = {
      "145",
      "146",
      "147",
      "155",
      "156",
      "159",
      "164",
      "166",
      "33",
      "75",
      "90",
      "Alfetta",
      "Brera",
      "Giulietta",
      "GT",
      "GTV",
      "MiTo",
      "Spider",
 },
 
 ["Audi"]={
      "100",
      "200",
      "80",
      "90",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Allroad",
      "Coupe",
      "Q3",
      "Q5",
      "Q7",
      "S6",
      "S8",
      "TT",
      "V8",
 },
 
 ["BMW"]={

      "1",
      "1 E87",
      "1 F20",
      "3",
      "3 E21",
      "3 E30",
      "3 E36",
      "3 E46",
      "3 E90",
      "3 E91",
      "3 E92",
      "3 E93",
      "3 F30",
      "3 F31",
      "3 GT F34",
      "5",
      "5 E28",
      "5 E34",
      "5 E39",
      "5 E60",
      "5 E61",
      "5 F10",
      "5 F11",
      "5 GT F07",
      "6",
      "6 E63",
      "6 F12",
      "6 Grand Coupe F06",
      "7",
      "7 E32",
      "7 E38",
      "7 E65",
      "7 E66",
      "7 F01",
      "7 F02",
      "8",
      "i3",
      "M3",
      "M5",
      "M6",
      "X1",
      "X3",
      "X3 E83",
      "X3 F25",
      "X5",
      "X5 E53",
      "X5 E70",
      "X5 F15",
      "X6",
      "Z1",
      "Z3",
      "Z4",
      "Z8",

 ["Buick"] = 

      "Century",
      "Enclave",
      "Lacrosse",
      "Le Sabre",
      "Park-Avenue",
      "Rainier",
      "Randevu",
      "Regal",
      "Riviera",
      "Roadmaster",
      "Skylark",
Cadillac

      "ATS",
      "BLS",
      "Catera",
      "CTS",
      "Deville",
      "DTS",
      "Eldorado",
      "Escalade",
      "Evoq",
      "Fleetwood",
      "Seville",
      "SRX",
      "STS",
      "XLR",
Chery

      "A5",
      "Amulet",
      "Bonus",
      "Fora",
      "Kimo",
      "QQ",
      "Tiggo",
      "Very",
Chevrolet

      "Alero",
      "Astro",
      "Avalanche",
      "Aveo",
      "Beretta",
      "Blazer",
      "Camaro",
      "Caprice",
      "Captiva",
      "Cavalier",
      "Chevy Van",
      "Cobalt",
      "Colorado",
      "Corsica",
      "Corvette",
      "Cruze",
      "Epica",
      "Equinox",
      "Evanda",
      "Express",
      "HHR",
      "Impala",
      "Kalos",
      "Lacetti",
      "Lanos",
      "Lumina",
      "Lumina-APV",
      "Malibu",
      "Matiz",
      "Metro",
      "Niva",
      "Nubira",
      "Orlando",
      "Prizm",
      "Rezzo",
      "S10",
      "Sens",
      "Silverado",
      "Spark",
      "Suburban",
      "Tacuma",
      "Tahoe",
      "Tracker",
      "TrailBlazer",
      "Transsport",
      "Uplander",
      "Venture",
      "Volt",
Chrysler

      "200",
      "300C",
      "300M",
      "Cirrus",
      "Concorde",
      "Crossfire",
      "Daytona",
      "Grand Voyager",
      "Intrepid",
      "Laser",
      "Le Baron",
      "LHS",
      "Neon",
      "New-Yorker",
      "Pacifica",
      "PT-Cruiser",
      "Saratoga",
      "Sebring",
      "Shadow",
      "Stratus",
      "Town-Country",
      "Viper",
      "Vision",
      "Voyager",
Citroen

      "AX",
      "Berlingo",
      "BX",
      "C-Crosser",
      "C-Elysee",
      "C1",
      "C15",
      "C2",
      "C3",
      "C3 Picasso",
      "C4",
      "C4 Grand Picasso",
      "C4 Picasso",
      "C5",
      "C6",
      "C8",
      "DS3",
      "DS4",
      "Evasion",
      "J5",
      "Jumper",
      "Jumpy",
      "Nemo",
      "Picasso",
      "Relay",
      "Saxo",
      "Xantia",
      "XM",
      "Xsara",
      "Xsara Picasso",
      "ZX",
Dacia

      "Duster",
      "Logan",
      "Nova",
      "Sandero",
      "Solenza",
Daewoo

      "Damas",
      "Espero",
      "Evanda",
      "Gentra",
      "Kalos",
      "Korando",
      "Lacetti",
      "Lanos",
      "Leganza",
      "Magnus",
      "Matiz",
      "Musso",
      "Nexia",
      "Nubira",
      "Rezzo",
      "Sens",
      "Tacuma",
      "Tico",
DAF

      "400",
      "45",
      "95",
      "CF",
      "LF",
      "XF",
Daihatsu

      "Applause",
      "Charade",
      "Copen",
      "Cuore",
      "Domino",
      "Feroza",
      "Gran Move",
      "Materia",
      "Move",
      "Rocky",
      "Sirion",
      "Storia",
      "Terios",
      "Trevis",
      "YRV",
Dodge

      "Avenger",
      "Caliber",
      "Caravan",
      "Challenger",
      "Charger",
      "Commander",
      "Dakota",
      "Dart",
      "Daytona",
      "Durango",
      "Grand Caravan",
      "Intrepid",
      "Journey",
      "Magnum",
      "Neon",
      "Nitro",
      "Ram",
      "Sebring",
      "Shadow",
      "Spirit",
      "Stealth",
      "Stratus",
Fiat

      "500",
      "Albea",
      "Barchetta",
      "Brava",
      "Bravo",
      "Cinquecento",
      "Coupe",
      "Croma",
      "Doblo",
      "Ducato",
      "Fiorino",
      "Freemont",
      "Grande Punto",
      "Idea",
      "Linea",
      "Marea",
      "Marea Weekend",
      "Multipla",
      "Palio",
      "Panda",
      "Punto",
      "Qubo",
      "Regata",
      "Scudo",
      "Sedici",
      "Seicento",
      "Siena",
      "Stilo",
      "Strada",
      "Talento",
      "Tempra",
      "Tipo",
      "Ulysse",
      "Uno",
Ford

      "500",
      "B-Max ",
      "C-Max",
      "Contour",
      "Cougar",
      "Courier",
      "Crown-Victoria",
      "Econoline",
      "Econovan",
      "Ecosport",
      "Edge",
      "Escape",
      "Escort",
      "Excursion",
      "Expedition",
      "Explorer",
      "F",
      "Fiesta",
      "Focus",
      "Fusion",
      "Galaxy",
      "Granada",
      "Ka",
      "Kuga",
      "Maverick",
      "Mondeo",
      "Mustang",
      "Orion",
      "Probe",
      "Puma",
      "Ranger",
      "S-Max",
      "Scorpio",
      "Sierra",
      "Taunus",
      "Taurus",
      "Tourneo",
      "Tourneo Connect",
      "Transit",
      "Transit Connect",
      "Transit Custom",
      "Windstar",
"GMC",

      "Acadia",
      "Envoy",
      "Jimmy",
      "Safari",
      "Savana",
      "Sierra",
      "Sonoma",
      "Suburban",
      "Tayfun",
      "Terrain",
      "Yukon",
"Great-Wall",

      "Coolbear",
      "Deer",
      "Hover",
      "Pegasus",
      "Safe",
      "Wingle",
"Honda",
"",
      "Accord",
      "City",
      "Civic",
      "Concerto",
      "CR-V",
      "CR-X",
      "CR-Z",
      "Crosstour",
      "Element",
      "Fit",
      "FR-V",
      "HR-V",
      "Insight",
      "Integra",
      "Jazz",
      "Legend",
      "Logo",
      "Odyssey",
      "Passport",
      "Pilot",
      "Prelude",
      "Ridgeline",
      "S2000",
      "Shuttle",
      "Stream",
"Hummer",
"",
      "H1",
      "H2",
      "H3",
"Hyundai",
"",
      "Accent",
      "Amico",
      "Atos",
      "Coupe",
      "Elantra",
      "Equus",
      "Excel",
      "Galloper",
      "Genesis",
      "Getz",
      "Grandeur",
      "H1",
      "H100",
      "H200",
      "HD120",
      "HD72",
      "i10",
      "i20",
      "i30",
      "i40",
      "ix20",
      "ix35",
      "ix55",
      "Lantra",
      "Matrix",
      "Pony",
      "S Coupe",
      "Santa Fe",
      "Santamo",
      "Solaris",
      "Sonata",
      "Starex",
      "Terracan",
      "Tiburon",
      "Trajet",
      "Tucson",
      "Veloster",
      "Veracruz",
      "XG",
"IFA",
"",
      "50",
"Infiniti",
"",
      "EX",
      "FX",
      "G",
      "I",
      "J",
      "JX",
      "M",
      "Q",
      "QX",
"Iran-Khodro",
"",
      "Samand",
"Isuzu",
"",
      "Axiom",
      "Campo",
      "Gemini",
      "Midi",
      "Rodeo",
      "Trooper",
"Iveco",
"",
      "Daily",
      "Eurocargo",
      "Eurostar",
      "Eurotech",
      "Stralis",
      "Turbo Daily",
      "Turbostar",
"Jaguar",
"",
      "S-Type",
      "X-Type",
      "XF",
      "XJ",
      "XJR",
      "XJS",
      "XK",
      "XKR",
"Jeep",
"",
      "Cherokee",
      "Commander",
      "Compass",
      "Grand Cherokee",
      "Liberty",
      "Patriot",
      "Wrangler",
"Kia",
"",
      "Besta",
      "Bongo",
      "Carens",
      "Carnival",
      "Ceed",
      "Cerato",
      "Clarus",
      "Joice",
      "K2700",
      "Magentis",
      "Mohave",
      "Opirus",
      "Optima",
      "Picanto",
      "Pregio",
      "Pride",
      "Quoris",
      "Rio",
      "Sedona",
      "Sephia",
      "Shuma",
      "Sorento",
      "Soul",
      "Spectra",
      "Sportage",
      "Venga",
"Lada (¬¿«)",
"",
      "2101",
      "2102",
      "2103",
      "2104",
      "2105",
      "2106",
      "2107",
      "2108",
      "2109",
      "21099",
      "2110",
      "2111",
      "Granta",
      "Kalina",
      "Largus",
      "Priora",
      "ŒÍ‡",
"Lancia",
"",
      "Dedra",
      "Delta",
      "Kappa",
      "Lybra",
      "Musa",
      "Phedra",
      "Thema",
      "Thesis",
      "Ypsilon",
      "Zeta",
"Land-Rover",
"",
      "Defender",
      "Discovery",
      "Evoque",
      "Freelander",
      "Range Rover",
      "Range Rover Sport",
"LDV",
"",
      "Convoy",
      "Maxus",
      "Pilot",
"Lexus",
"",
      "CT",
      "ES",
      "GS",
      "GX",
      "HS",
      "IS",
      "LS",
      "LX",
      "RX",
      "SC",
"Lincoln",
"",
      "Aviator",
      "Continental",
      "LS",
      "Mark",
      "MKX",
      "Navigator",
      "Towncar",
"MAN",
"",
      "10150",
      "14232",
      "18272",
      "19364",
      "19372",
      "19403",
      "8150",
      "8163",
      "TGA",
      "TGL",
      "TGX",
"Mazda",
"",
      "121",
      "2",
      "3",
      "323",
      "323C",
      "323F",
      "323P",
      "323S",
      "5",
      "6",
      "626",
      "929",
      "B2500",
      "Bongo",
      "BT-50",
      "CX5",
      "CX7",
      "CX9",
      "Demio",
      "E2200",
      "Millenia",
      "MPV",
      "MX3",
      "MX5",
      "MX6",
      "Premacy",
      "Protege",
      "RX7",
      "RX8",
      "Tribute",
      "Xedos 6",
      "Xedos 9",
"Mercedes",
"",
      "100",
      "1117",
      "1317",
      "1735",
      "1834",
      "1838",
      "1840",
      "190 W201",
      "207",
      "208",
      "210",
      "308",
      "310",
      "407",
      "408",
      "409",
      "410",
      "508",
      "609",
      "709",
      "711",
      "811",
      "814",
      "A",
      "A W168",
      "A W169",
      "A W176",
      "Actros",
      "Atego",
      "Axor",
      "B W245",
      "B W246",
      "C",
      "C W202",
      "C W203",
      "C W204",
      "C W205",
      "CL",
      "CL W140",
      "CL W215",
      "CL W216",
      "CLC",
      "CLK",
      "CLK W208",
      "CLK W209",
      "CLS W218",
      "CLS W219",
      "E",
      "E W114",
      "E W123",
      "E W124",
      "E W210",
      "E W211",
      "E W212",
      "G",
      "G W460",
      "G W463",
      "GL",
      "GL X164",
      "GLA W156",
      "GLK X204",
      "ML",
      "ML W163",
      "ML W164",
      "ML W166",
      "R",
      "S",
      "S W126",
      "S W140",
      "S W220",
      "S W221",
      "SL",
      "SL W129",
      "SLK",
      "SLR",
      "Sprinter",
      "Vaneo",
      "Vario",
      "Viano",
      "Vito",
      "Vito W638",
      "Vito W639",
"MG",
"",
      "NGF",
      "TF",
      "ZR",
      "ZS",
      "ZT",
      "ZT-T",
"Mini",
"",
      "Clubman",
      "Cooper",
      "Countryman",
      "One",
      "Paceman",
"Mitsubishi",
"",
      "3000GT",
      "ASX",
      "Canter",
      "Carisma",
      "Colt",
      "Delica",
      "Diamante",
      "Eclipse",
      "Endeavor",
      "FTO",
      "Galant",
      "Grandis",
      "L200",
      "L300",
      "L400",
      "Lancer",
      "Montero",
      "Montero Sport",
      "Outlander",
      "Pajero",
      "Pajero Pinin",
      "Pajero Sport",
      "RVR",
      "Sigma",
      "Space Gear",
      "Space Runner",
      "Space Star",
      "Space Wagon",
"Nissan",
"",
      "100NX",
      "200SX",
      "350Z",
      "Almera",
      "Almera Tino",
      "Altima",
      "Armada",
      "Bluebird",
      "Cabstar",
      "Cherry",
      "Expert",
      "Frontier",
      "Interstar",
      "Juke",
      "Kubistar",
      "Laurel",
      "Leaf",
      "Maxima",
      "Maxima QX",
      "Micra",
      "Murano",
      "Navara",
      "Note",
      "NP3000",
      "NV200",
      "Pathfinder",
      "Patrol",
      "Pixo",
      "Prairie",
      "Presea",
      "Primastar",
      "Primera",
      "Pulsar",
      "Qashqai",
      "Quest",
      "Rogue",
      "Sentra",
      "Serena",
      "Skyline",
      "Sunny",
      "Teana",
      "Terrano",
      "Tiida",
      "Titan",
      "Trade",
      "Vanette",
      "X-Terra",
      "X-Trail",
"Opel",
"",
      "Agila",
      "Antara",
      "Arena",
      "Ascona",
      "Astra",
      "Calibra",
      "Combo",
      "Corsa",
      "Frontera",
      "Insignia",
      "Kadett",
      "Meriva",
      "Mokka",
      "Monterey",
      "Movano",
      "Omega",
      "Rekord",
      "Senator",
      "Signum",
      "Sintra",
      "Tigra",
      "Vectra",
      "Vivaro",
      "Zafira",
"Peugeot",
"",
      "1007",
      "106",
      "107",
      "2008",
      "205",
      "206",
      "207",
      "208",
      "3008",
      "301",
      "305",
      "306",
      "307",
      "307CC",
      "308",
      "309",
      "4007",
      "4008",
      "405",
      "406",
      "406 Coupe",
      "407",
      "407 Coupe",
      "408",
      "5008",
      "508",
      "605",
      "607",
      "806",
      "807",
      "Bipper",
      "Boxer",
      "Expert",
      "J5",
      "Partner",
      "RCZ",
"Pontiac",
"",
      "Aztek",
      "Firebird",
      "G5",
      "G6",
      "Grand Am",
      "Grand Prix",
      "Montana",
      "Trans-Sport",
      "Vibe",
"Porsche",
"",
      "911",
      "Boxster",
      "Cayenne",
      "Cayman",
      "Macan",
      "Panamera",
"Proton",
"",
      "400",
      "Gen",
      "Persona",
      "Satria",
      "Wira",
"Renault",
"",
      "11",
      "19",
      "21",
      "25",
      "5",
      "9",
      "Avantime",
      "Clio",
      "Dokker",
      "Duster",
      "Espace",
      "Fluence",
      "Grand Espace",
      "Grand Scenic",
      "Kangoo",
      "Kaptur",
      "Koleos",
      "Laguna",
      "Latitude",
      "Lodgy",
      "Logan",
      "Magnum",
      "Major",
      "Manager",
      "Mascott",
      "Master",
      "Megane",
      "Midlum",
      "Modus",
      "Premium",
      "Rapid",
      "Rodeo",
      "Safrane",
      "Sandero",
      "Sandero Stepway",
      "Scenic",
      "Symbol",
      "Trafic",
      "Twingo",
      "Vel Satis",
"Rover",
"",
      "100",
      "111",
      "114",
      "200",
      "211",
      "213",
      "214",
      "216",
      "218",
      "220",
      "25",
      "400",
      "414",
      "416",
      "418",
      "420",
      "425",
      "45",
      "600",
      "618",
      "620",
      "623",
      "75",
      "800",
      "820",
      "825",
      "827",
      "Metro",
      "Streetwise",
"Saab",
"",
      "9-2X",
      "9-3",
      "9-5",
      "9-6",
      "9-7",
      "900",
      "9000",
"Saturn",
"",
      "Aura",
      "Ion",
      "Outlook",
      "Relay",
      "Vue",
"Scania",
"",
      "113",
      "114",
      "124",
      "143",
      "144",
      "R420",
"Seat",
"",
      "Alhambra",
      "Altea",
      "Arosa",
      "Ateca",
      "Cordoba",
      "Exeo",
      "Ibiza",
      "Inca",
      "Leon",
      "Terra",
      "Toledo",
"Skoda",
"",
      "Citigo",
      "Fabia",
      "Favorit",
      "Felicia",
      "Forman",
      "Octavia",
      "Praktik",
      "Rapid",
      "Roomster",
      "Superb",
      "Yeti",
"Smart",
"",
      "Coupe",
      "Forfour",
      "Fortwo",
      "Roadster",
"SsangYong",
"",
      "Actyon",
      "Korando",
      "Kyron",
      "Musso",
      "Rexton",
      "Rodius",
"Subaru",
"",
      "Forester",
      "Impreza",
      "Justy",
      "Legacy",
      "Leone",
      "Libero",
      "Outback",
      "Tribeca",
      "XV",
"Suzuki",
"",
      "Alto",
      "Baleno",
      "Forenza",
      "Grand Vitara",
      "Ignis",
      "Jimny",
      "Kizashi",
      "Liana",
      "Samurai",
      "Splash",
      "Swift",
      "SX4",
      "Vitara",
      "Wagon R",
      "XL7",
"Toyota",
"",
      "4Runner",
      "Auris",
      "Avalon",
      "Avensis",
      "Avensis Verso",
      "Aygo",
      "Camry",
      "Carina",
      "Carina 2",
      "Carina E",
      "Celica",
      "Chaser",
      "Corolla",
      "Corolla Verso",
      "Crown",
      "Echo",
      "Estima",
      "GT86",
      "Hiace",
      "Highlander",
      "Hilux",
      "iQ",
      "Land Cruiser",
      "Land Cruiser Prado",
      "Matrix",
      "Paseo",
      "Picnic",
      "Previa",
      "Prius",
      "RAV4",
      "Sequoia",
      "Sienna",
      "Solara",
      "Starlet",
      "Supra",
      "TownAce",
      "Tundra",
      "Urban Cruiser",
      "Venza",
      "Verso",
      "Yaris",
      "Yaris Verso",
"Volkswagen",
"",
      "Amarok",
      "Beetle",
      "Bora",
      "Caddy",
      "Caravelle",
      "Corrado",
      "Crafter",
      "EOS",
      "Fox",
      "Golf",
      "Golf Plus",
      "Jetta",
      "LT",
      "Lupo",
      "Multivan",
      "Passat",
      "Phaeton",
      "Polo",
      "Santana",
      "Scirocco",
      "Sharan",
      "Tiguan",
      "Touareg",
      "Touran",
      "Transporter",
      "Up",
      "Vento",
"Volvo",
"",
      "240",
      "340",
      "360",
      "440",
      "460",
      "480",
      "740",
      "760",
      "850",
      "940",
      "960",
      "C30",
      "C70",
      "F",
      "FH",
      "FL",
      "FM",
      "S40",
      "S60",
      "S70",
      "S80",
      "S90",
      "V40",
      "V50",
      "V60",
      "V70",
      "V90",
      "XC60",
      "XC70",
      "XC90",
"√¿«",
"",
      "21",
      "24",
      "2410",
      "31029",
      "3110",
      "53",
      "66",
      "¬‡Î‰‡È",
      "√‡ÁÂÎ¸",
      "—Ó·ÓÎ¸",
"«¿«",
"",
      "968M",
      "“‡‚Ëˇ",
" ‡Ï¿«",
"",
      "6520",
"ÀÛ¿«",
"",
      "1301",
      "965",
      "967Ã",
      "968",
      "969",
"Ã¿«",
"",
      "4370",
      "54323",
      "544008",
      "5516",
      "5551",
"ÃÓÒÍ‚Ë˜",
"",
      "2140",
      "2141",
      "412",
"”¿«",
"",
      "3151",
      "3160",
      "3162",
      "3303",
      "3962",
      "452",
      "469",
      "Hunter",
      "Patriot",
